### ISSUE TITLE
whitespace handling in function regex

### ISSUE THREAD

**Issue by jonschlinkert** [jonschlinkert/parse-code-context#1]
Per https://github.com/regexps/function-regex/issues/2#issuecomment-84488091.

> that regex shares several issues

@chocolateboy I think the first example you gave is potentially an issue, `function  foo () {} // > 1 space`, but since the other is intentionally defined in the regex, `[ \t]`, maybe that's more of a feature request given that it's not really a javascript parser, just code context?

**Comment by chocolateboy** [comment]
I'm not familiar with this package, so my comment may not be relevant if handling real-world code is out of scope.

But for anything beyond basic grepping, I recommend using a parser rather than regexes if you want to avoid playing whack-a-mole with edge cases. There's an Esprima-based function parser [here](https://github.com/twolfson/function-to-string).

**Comment by jonschlinkert** [comment]
> if you want to avoid playing whack-a-mole with edge cases.

lol good line. 

> I recommend using a parser rather than regexes

I mostly use this for generating documentation. You're right though, I've played [whack-a-mole](https://github.com/search?utf8=%E2%9C%93&q=user%3Ajonschlinkert+parse&type=Repositories&ref=searchresults) with far too many edge cases. At some point I might start using a real parser even for the code comments since the use cases are getting more complex, but speed-wise real parsers are orders of magnitude slower and I haven't really had any problems with this yet. 

good feedback though, thank you

**Comment by jonschlinkert** [comment]
closing since this hasn't really caused an issue
